channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=22.0.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.0.0
  - lz4==3.1.3
  - numpy==1.23.5
  - psutil==7.0.0
  - scikit-learn==1.3.2
  - scipy==1.14.1
name: mlflow-env
